In [1]:
import numpy as np
import pandas as pd
import scipy as sp
from scipy import stats
from matplotlib import pyplot as plt
import seaborn as sns
sns.set()
%precision 3
%matplotlib inline

In [2]:
fish_5 = np.array([2, 3, 4, 5, 6])
fish_5

array([2, 3, 4, 5, 6])

In [3]:
np.random.choice(fish_5, size=1, replace=False)

array([3])

In [4]:
np.random.choice(fish_5, size=3, replace=False)

array([2, 5, 4])

In [5]:
np.random.seed(1)
sp.mean(
    np.random.choice(fish_5, size=3, replace=False)
)

4.333333333333333

In [7]:
fish_100000 = pd.read_csv('3-4-1-fish_length_100000.csv')['length']
fish_100000.head()

0    5.297442
1    3.505566
2    3.572546
3    3.135979
4    4.689275
Name: length, dtype: float64

In [8]:
len(fish_100000)

100000